AWSAccountID: "649037252677"
AWSProfileName: "default"
AWSProfileRegion: "us-east-1"

App: "DevApplication"
Environment: "dev"
Version: "0.0.0"
Build: "0"

GithubSecretName: "CDKPipelines/Dev/GithubSecret"
GithubRepo: "organization/repo"
GithubBranch: "main"

Parameters:
  TestParameter: "DevFooBar"